package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellidos;
     private String direccion;
     private Set facmaes = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String nombre, String apellidos) {
        this.nombre = nombre;
        this.apellidos = apellidos;
    }
    public Clientes(String nombre, String apellidos, String direccion, Set facmaes) {
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.direccion = direccion;
       this.facmaes = facmaes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set getFacmaes() {
        return this.facmaes;
    }
    
    public void setFacmaes(Set facmaes) {
        this.facmaes = facmaes;
    }




}


