package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


/**
 * Facdet generated by hbm2java
 */
public class Facdet  implements java.io.Serializable {


     private Integer idRow;
     private Facmae facmae;
     private Producto producto;
     private int nro_item;
     private double cantidad;
     private double preciovta;
     private double subtotal;


    public Facdet() {
    }

     public Facdet(int nro_item, Producto producto,double cantidad, double preciovta, double subtotal) {
       this.producto = producto;
       this.nro_item = nro_item;
       this.cantidad = cantidad;
       this.preciovta = preciovta;
       this.subtotal = subtotal;
    }

    
    public Facdet(Facmae facmae, Producto producto, int nro_item, double cantidad, double preciovta, double subtotal) {
       this.facmae = facmae;
       this.producto = producto;
       this.nro_item = nro_item;
       this.cantidad = cantidad;
       this.preciovta = preciovta;
       this.subtotal = subtotal;
    }
   
    public Integer getIdRow() {
        return this.idRow;
    }
    
    public void setIdRow(Integer idRow) {
        this.idRow = idRow;
    }
    public Facmae getFacmae() {
        return this.facmae;
    }
    
    public void setFacmae(Facmae facmae) {
        this.facmae = facmae;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    public int getNro_item() {
        return nro_item;
    }

    public void setNro_item(int nro_item) {
        this.nro_item = nro_item;
    }
   
  
    
    
    
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getPreciovta() {
        return this.preciovta;
    }
    
    public void setPreciovta(double preciovta) {
        this.preciovta = preciovta;
    }
    public double getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(double subtotal) {
        this.subtotal = subtotal;
    }




}


