package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String codproducto;
     private String nomproducto;
     private double costoUnitario;
     private double precioVenta;
     private Set facdets = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String codproducto, String nomproducto, double costoUnitario, double precioVenta) {
        this.codproducto = codproducto;
        this.nomproducto = nomproducto;
        this.costoUnitario = costoUnitario;
        this.precioVenta = precioVenta;
    }
    public Producto(String codproducto, String nomproducto, double costoUnitario, double precioVenta, Set facdets) {
       this.codproducto = codproducto;
       this.nomproducto = nomproducto;
       this.costoUnitario = costoUnitario;
       this.precioVenta = precioVenta;
       this.facdets = facdets;
    }
   
    public String getCodproducto() {
        return this.codproducto;
    }
    
    public void setCodproducto(String codproducto) {
        this.codproducto = codproducto;
    }
    public String getNomproducto() {
        return this.nomproducto;
    }
    
    public void setNomproducto(String nomproducto) {
        this.nomproducto = nomproducto;
    }
    public double getCostoUnitario() {
        return this.costoUnitario;
    }
    
    public void setCostoUnitario(double costoUnitario) {
        this.costoUnitario = costoUnitario;
    }
    public double getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(double precioVenta) {
        this.precioVenta = precioVenta;
    }
    public Set getFacdets() {
        return this.facdets;
    }
    
    public void setFacdets(Set facdets) {
        this.facdets = facdets;
    }




}


