package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1



/**
 * TcontactoEmpleado generated by hbm2java
 */
public class TcontactoEmpleado  implements java.io.Serializable {


     private int id;
     private Integer idContacto;
     private Integer idEmpleado;
     private String descripcion;

    public TcontactoEmpleado() {
    }

	
    public TcontactoEmpleado(int id) {
        this.id = id;
    }
    public TcontactoEmpleado(int id, Integer idContacto, Integer idEmpleado, String descripcion) {
       this.id = id;
       this.idContacto = idContacto;
       this.idEmpleado = idEmpleado;
       this.descripcion = descripcion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


