package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1



/**
 * TctaBcoEmpleado generated by hbm2java
 */
public class TctaBcoEmpleado  implements java.io.Serializable {


     private String nroCuenta;
     private byte snActiva;
     private int idEmpleado;

    public TctaBcoEmpleado() {
    }

    public TctaBcoEmpleado(String nroCuenta, byte snActiva, int idEmpleado) {
       this.nroCuenta = nroCuenta;
       this.snActiva = snActiva;
       this.idEmpleado = idEmpleado;
    }
   
    public String getNroCuenta() {
        return this.nroCuenta;
    }
    
    public void setNroCuenta(String nroCuenta) {
        this.nroCuenta = nroCuenta;
    }
    public byte getSnActiva() {
        return this.snActiva;
    }
    
    public void setSnActiva(byte snActiva) {
        this.snActiva = snActiva;
    }
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }




}


