package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TdeptoPais generated by hbm2java
 */
public class TdeptoPais  implements java.io.Serializable {


     private Integer id;
     private Tpais tpais;
     private String nomDepto;
     private Set templeadoses = new HashSet(0);
     private Set tmunicipioses = new HashSet(0);

    public TdeptoPais() {
    }

	
    public TdeptoPais(Tpais tpais, String nomDepto) {
        this.tpais = tpais;
        this.nomDepto = nomDepto;
    }
    public TdeptoPais(Tpais tpais, String nomDepto, Set templeadoses, Set tmunicipioses) {
       this.tpais = tpais;
       this.nomDepto = nomDepto;
       this.templeadoses = templeadoses;
       this.tmunicipioses = tmunicipioses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tpais getTpais() {
        return this.tpais;
    }
    
    public void setTpais(Tpais tpais) {
        this.tpais = tpais;
    }
    public String getNomDepto() {
        return this.nomDepto;
    }
    
    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }
    public Set getTempleadoses() {
        return this.templeadoses;
    }
    
    public void setTempleadoses(Set templeadoses) {
        this.templeadoses = templeadoses;
    }
    public Set getTmunicipioses() {
        return this.tmunicipioses;
    }
    
    public void setTmunicipioses(Set tmunicipioses) {
        this.tmunicipioses = tmunicipioses;
    }




}


