package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Templeados generated by hbm2java
 */
public class Templeados  implements java.io.Serializable {


     private Integer id;
     private Tcargo tcargo;
     private TdeptoPais tdeptoPais;
     private Tmunicipios tmunicipios;
     private Tprofesion tprofesion;
     private String codEmpleado;
     private String primerApellido;
     private String segundoApellido;
     private String nombres;
     private String nroIdentidad;
     private Date fechaNac;
     private String lugarNacimiento;
     private char sexo;
     private char estadoCivil;
     private BigDecimal sueldoBruto;
     private Date fecAlta;
     private Date fecBaja;
     private char tipoEmpleado;
     private String creadoPor;
     private String modificadoPor;
     private Date fecModificado;
     private int idPais;
     private int idDeptoEmp;
     private Set tmovEmpleados = new HashSet(0);

    public Templeados() {
    }

	
    public Templeados(Tcargo tcargo, TdeptoPais tdeptoPais, Tmunicipios tmunicipios, Tprofesion tprofesion, String codEmpleado, String primerApellido, String nombres, String nroIdentidad, Date fechaNac, String lugarNacimiento, char sexo, char estadoCivil, BigDecimal sueldoBruto, Date fecAlta, char tipoEmpleado, String creadoPor, int idPais, int idDeptoEmp) {
        this.tcargo = tcargo;
        this.tdeptoPais = tdeptoPais;
        this.tmunicipios = tmunicipios;
        this.tprofesion = tprofesion;
        this.codEmpleado = codEmpleado;
        this.primerApellido = primerApellido;
        this.nombres = nombres;
        this.nroIdentidad = nroIdentidad;
        this.fechaNac = fechaNac;
        this.lugarNacimiento = lugarNacimiento;
        this.sexo = sexo;
        this.estadoCivil = estadoCivil;
        this.sueldoBruto = sueldoBruto;
        this.fecAlta = fecAlta;
        this.tipoEmpleado = tipoEmpleado;
        this.creadoPor = creadoPor;
        this.idPais = idPais;
        this.idDeptoEmp = idDeptoEmp;
    }
    public Templeados(Tcargo tcargo, TdeptoPais tdeptoPais, Tmunicipios tmunicipios, Tprofesion tprofesion, String codEmpleado, String primerApellido, String segundoApellido, String nombres, String nroIdentidad, Date fechaNac, String lugarNacimiento, char sexo, char estadoCivil, BigDecimal sueldoBruto, Date fecAlta, Date fecBaja, char tipoEmpleado, String creadoPor, String modificadoPor, Date fecModificado, int idPais, int idDeptoEmp, Set tmovEmpleados) {
       this.tcargo = tcargo;
       this.tdeptoPais = tdeptoPais;
       this.tmunicipios = tmunicipios;
       this.tprofesion = tprofesion;
       this.codEmpleado = codEmpleado;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.nombres = nombres;
       this.nroIdentidad = nroIdentidad;
       this.fechaNac = fechaNac;
       this.lugarNacimiento = lugarNacimiento;
       this.sexo = sexo;
       this.estadoCivil = estadoCivil;
       this.sueldoBruto = sueldoBruto;
       this.fecAlta = fecAlta;
       this.fecBaja = fecBaja;
       this.tipoEmpleado = tipoEmpleado;
       this.creadoPor = creadoPor;
       this.modificadoPor = modificadoPor;
       this.fecModificado = fecModificado;
       this.idPais = idPais;
       this.idDeptoEmp = idDeptoEmp;
       this.tmovEmpleados = tmovEmpleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tcargo getTcargo() {
        return this.tcargo;
    }
    
    public void setTcargo(Tcargo tcargo) {
        this.tcargo = tcargo;
    }
    public TdeptoPais getTdeptoPais() {
        return this.tdeptoPais;
    }
    
    public void setTdeptoPais(TdeptoPais tdeptoPais) {
        this.tdeptoPais = tdeptoPais;
    }
    public Tmunicipios getTmunicipios() {
        return this.tmunicipios;
    }
    
    public void setTmunicipios(Tmunicipios tmunicipios) {
        this.tmunicipios = tmunicipios;
    }
    public Tprofesion getTprofesion() {
        return this.tprofesion;
    }
    
    public void setTprofesion(Tprofesion tprofesion) {
        this.tprofesion = tprofesion;
    }
    public String getCodEmpleado() {
        return this.codEmpleado;
    }
    
    public void setCodEmpleado(String codEmpleado) {
        this.codEmpleado = codEmpleado;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getNroIdentidad() {
        return this.nroIdentidad;
    }
    
    public void setNroIdentidad(String nroIdentidad) {
        this.nroIdentidad = nroIdentidad;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public String getLugarNacimiento() {
        return this.lugarNacimiento;
    }
    
    public void setLugarNacimiento(String lugarNacimiento) {
        this.lugarNacimiento = lugarNacimiento;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public char getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(char estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public BigDecimal getSueldoBruto() {
        return this.sueldoBruto;
    }
    
    public void setSueldoBruto(BigDecimal sueldoBruto) {
        this.sueldoBruto = sueldoBruto;
    }
    public Date getFecAlta() {
        return this.fecAlta;
    }
    
    public void setFecAlta(Date fecAlta) {
        this.fecAlta = fecAlta;
    }
    public Date getFecBaja() {
        return this.fecBaja;
    }
    
    public void setFecBaja(Date fecBaja) {
        this.fecBaja = fecBaja;
    }
    public char getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(char tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public String getCreadoPor() {
        return this.creadoPor;
    }
    
    public void setCreadoPor(String creadoPor) {
        this.creadoPor = creadoPor;
    }
    public String getModificadoPor() {
        return this.modificadoPor;
    }
    
    public void setModificadoPor(String modificadoPor) {
        this.modificadoPor = modificadoPor;
    }
    public Date getFecModificado() {
        return this.fecModificado;
    }
    
    public void setFecModificado(Date fecModificado) {
        this.fecModificado = fecModificado;
    }
    public int getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(int idPais) {
        this.idPais = idPais;
    }
    public int getIdDeptoEmp() {
        return this.idDeptoEmp;
    }
    
    public void setIdDeptoEmp(int idDeptoEmp) {
        this.idDeptoEmp = idDeptoEmp;
    }
    public Set getTmovEmpleados() {
        return this.tmovEmpleados;
    }
    
    public void setTmovEmpleados(Set tmovEmpleados) {
        this.tmovEmpleados = tmovEmpleados;
    }




}


