package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1



/**
 * Testado generated by hbm2java
 */
public class Testado  implements java.io.Serializable {


     private Integer id;
     private String desc;

    public Testado() {
    }

    public Testado(String desc) {
       this.desc = desc;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


