package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Tmovimientos generated by hbm2java
 */
public class Tmovimientos  implements java.io.Serializable {


     private Integer id;
     private Toperacion toperacion;
     private String descripcion;
     private char tipo;
     private BigDecimal valor;
     private byte snActiva;
     private Set tmovEmpleados = new HashSet(0);

    public Tmovimientos() {
    }

	
    public Tmovimientos(Toperacion toperacion, String descripcion, char tipo, BigDecimal valor, byte snActiva) {
        this.toperacion = toperacion;
        this.descripcion = descripcion;
        this.tipo = tipo;
        this.valor = valor;
        this.snActiva = snActiva;
    }
    public Tmovimientos(Toperacion toperacion, String descripcion, char tipo, BigDecimal valor, byte snActiva, Set tmovEmpleados) {
       this.toperacion = toperacion;
       this.descripcion = descripcion;
       this.tipo = tipo;
       this.valor = valor;
       this.snActiva = snActiva;
       this.tmovEmpleados = tmovEmpleados;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Toperacion getToperacion() {
        return this.toperacion;
    }
    
    public void setToperacion(Toperacion toperacion) {
        this.toperacion = toperacion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public byte getSnActiva() {
        return this.snActiva;
    }
    
    public void setSnActiva(byte snActiva) {
        this.snActiva = snActiva;
    }
    public Set getTmovEmpleados() {
        return this.tmovEmpleados;
    }
    
    public void setTmovEmpleados(Set tmovEmpleados) {
        this.tmovEmpleados = tmovEmpleados;
    }




}


