package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TmovEmpleado generated by hbm2java
 */
public class TmovEmpleado  implements java.io.Serializable {


     private int id;
     private Templeados templeados;
     private Tmovimientos tmovimientos;
     private BigDecimal vlrMovimiento;
     private byte snActiva;

    public TmovEmpleado() {
    }

    public TmovEmpleado(int id, Templeados templeados, Tmovimientos tmovimientos, BigDecimal vlrMovimiento, byte snActiva) {
       this.id = id;
       this.templeados = templeados;
       this.tmovimientos = tmovimientos;
       this.vlrMovimiento = vlrMovimiento;
       this.snActiva = snActiva;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Templeados getTempleados() {
        return this.templeados;
    }
    
    public void setTempleados(Templeados templeados) {
        this.templeados = templeados;
    }
    public Tmovimientos getTmovimientos() {
        return this.tmovimientos;
    }
    
    public void setTmovimientos(Tmovimientos tmovimientos) {
        this.tmovimientos = tmovimientos;
    }
    public BigDecimal getVlrMovimiento() {
        return this.vlrMovimiento;
    }
    
    public void setVlrMovimiento(BigDecimal vlrMovimiento) {
        this.vlrMovimiento = vlrMovimiento;
    }
    public byte getSnActiva() {
        return this.snActiva;
    }
    
    public void setSnActiva(byte snActiva) {
        this.snActiva = snActiva;
    }




}


