package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tmunicipios generated by hbm2java
 */
public class Tmunicipios  implements java.io.Serializable {


     private Integer id;
     private TdeptoPais tdeptoPais;
     private Tpais tpais;
     private String nomMuni;
     private String codMunicipio;
     private Set templeadoses = new HashSet(0);

    public Tmunicipios() {
    }

	
    public Tmunicipios(TdeptoPais tdeptoPais, Tpais tpais, String nomMuni, String codMunicipio) {
        this.tdeptoPais = tdeptoPais;
        this.tpais = tpais;
        this.nomMuni = nomMuni;
        this.codMunicipio = codMunicipio;
    }
    public Tmunicipios(TdeptoPais tdeptoPais, Tpais tpais, String nomMuni, String codMunicipio, Set templeadoses) {
       this.tdeptoPais = tdeptoPais;
       this.tpais = tpais;
       this.nomMuni = nomMuni;
       this.codMunicipio = codMunicipio;
       this.templeadoses = templeadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TdeptoPais getTdeptoPais() {
        return this.tdeptoPais;
    }
    
    public void setTdeptoPais(TdeptoPais tdeptoPais) {
        this.tdeptoPais = tdeptoPais;
    }
    public Tpais getTpais() {
        return this.tpais;
    }
    
    public void setTpais(Tpais tpais) {
        this.tpais = tpais;
    }
    public String getNomMuni() {
        return this.nomMuni;
    }
    
    public void setNomMuni(String nomMuni) {
        this.nomMuni = nomMuni;
    }
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public Set getTempleadoses() {
        return this.templeadoses;
    }
    
    public void setTempleadoses(Set templeadoses) {
        this.templeadoses = templeadoses;
    }




}


