package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Toperacion generated by hbm2java
 */
public class Toperacion  implements java.io.Serializable {


     private Integer id;
     private String descripcion;
     private Set tmovimientoses = new HashSet(0);

    public Toperacion() {
    }

    public Toperacion(String descripcion, Set tmovimientoses) {
       this.descripcion = descripcion;
       this.tmovimientoses = tmovimientoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getTmovimientoses() {
        return this.tmovimientoses;
    }
    
    public void setTmovimientoses(Set tmovimientoses) {
        this.tmovimientoses = tmovimientoses;
    }




}


