package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tpais generated by hbm2java
 */
public class Tpais  implements java.io.Serializable {


     private Integer id;
     private String nomPais;
     private Set tmunicipioses = new HashSet(0);
     private Set tdeptoPaises = new HashSet(0);

    public Tpais() {
    }

	
    public Tpais(String nomPais) {
        this.nomPais = nomPais;
    }
    public Tpais(String nomPais, Set tmunicipioses, Set tdeptoPaises) {
       this.nomPais = nomPais;
       this.tmunicipioses = tmunicipioses;
       this.tdeptoPaises = tdeptoPaises;
    }
   
     public Tpais(int id, String nomPais) {
         this.id = id;
         this.nomPais = nomPais;
     }
     
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomPais() {
        return this.nomPais;
    }
    
    public void setNomPais(String nomPais) {
        this.nomPais = nomPais;
    }
    public Set getTmunicipioses() {
        return this.tmunicipioses;
    }
    
    public void setTmunicipioses(Set tmunicipioses) {
        this.tmunicipioses = tmunicipioses;
    }
    public Set getTdeptoPaises() {
        return this.tdeptoPaises;
    }
    
    public void setTdeptoPaises(Set tdeptoPaises) {
        this.tdeptoPaises = tdeptoPaises;
    }




}


