package modelo;
// Generated 05-13-2019 07:40:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tprofesion generated by hbm2java
 */
public class Tprofesion  implements java.io.Serializable {


     private Integer id;
     private String nomProfesion;
     private Set templeadoses = new HashSet(0);

    public Tprofesion() {
    }

    public Tprofesion(String nomProfesion, Set templeadoses) {
       this.nomProfesion = nomProfesion;
       this.templeadoses = templeadoses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomProfesion() {
        return this.nomProfesion;
    }
    
    public void setNomProfesion(String nomProfesion) {
        this.nomProfesion = nomProfesion;
    }
    public Set getTempleadoses() {
        return this.templeadoses;
    }
    
    public void setTempleadoses(Set templeadoses) {
        this.templeadoses = templeadoses;
    }




}


